[package]
name = "rxssh"
version = "0.1.1"
authors = ["Andy <andy@andy.codes>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmd = { path = "src/modules/cmd" }
ssh = { path = "src/modules/ssh" }