[package]
name = "ssh"
version = "0.1.0"
authors = ["Andy <andy@andy.codes>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9.1"